# Generated by Django 3.0.7 on 2020-06-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.SmallIntegerField()),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')])),
                ('birth', models.DateField()),
                ('tel', models.CharField(max_length=16)),
                ('addr', models.CharField(max_length=32)),
                ('grades', models.ManyToManyField(to='school.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('age', models.SmallIntegerField()),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')])),
                ('birth', models.DateField()),
                ('telphone', models.CharField(max_length=16)),
                ('addr', models.CharField(max_length=32)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Grade')),
            ],
        ),
    ]
